package ATM;

import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class Screen3 extends javax.swing.JFrame {
    
    private final static String CUSTOMER_NAME = "Akash Gilbert";
    
    //DecimalFormat df = new DecimalFormat("AED #,###,###,##0.00");
    
    public Screen3() {
        initComponents();
        scaleLabelIcon(lblHome, "/ATM/home.png");
        lblCustomerName.setText(CUSTOMER_NAME);
        //lblAvailableAmount.setText("AED " + String.format("%,.2f", availableAmount));
        //lblAvailableAmount.setText(df.format(availableAmount));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblAvailableAmount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCashWithdrawal = new javax.swing.JLabel();
        lblFundTransfer = new javax.swing.JLabel();
        lblAccountDetails = new javax.swing.JLabel();
        lblOtherServices = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 150, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CAPITAL BANKERS");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(158, 156, 159));
        jLabel2.setText("Toll Free:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 195, 197));
        jLabel3.setText("1800 0001 0001");

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/home.png"))); // NOI18N
        lblHome.setText("jLabel4");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(22, 22, 22));

        lblWelcome.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(22, 22, 22));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWelcome.setText("Available Balance -");
        lblWelcome.setToolTipText("");

        lblWelcome1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWelcome1.setText("Welcome back");
        lblWelcome1.setToolTipText("");

        lblCustomerName.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCustomerName.setText("Akash Gilbert !");
        lblCustomerName.setToolTipText("");

        lblAvailableAmount.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lblAvailableAmount.setForeground(new java.awt.Color(22, 22, 22));
        lblAvailableAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAvailableAmount.setText("AED 2,00,000.00");
        lblAvailableAmount.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(22, 22, 22));

        lblCashWithdrawal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/cash-withdrawal.png"))); // NOI18N
        lblCashWithdrawal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCashWithdrawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCashWithdrawalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCashWithdrawalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCashWithdrawalMouseExited(evt);
            }
        });

        lblFundTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/fund-transfer.png"))); // NOI18N
        lblFundTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAccountDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/account-details.png"))); // NOI18N
        lblAccountDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblOtherServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/other-services.png"))); // NOI18N
        lblOtherServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOtherServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOtherServicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOtherServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOtherServicesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCashWithdrawal)
                    .addComponent(lblAccountDetails))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOtherServices)
                    .addComponent(lblFundTransfer))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCashWithdrawal)
                    .addComponent(lblFundTransfer))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountDetails)
                    .addComponent(lblOtherServices))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvailableAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailableAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        scaleLabelIcon(lblHome, "/ATM/home-hover.png");
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        scaleLabelIcon(lblHome, "/ATM/home.png");
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        Screen1 screen1 = new Screen1();
        screen1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblCashWithdrawalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashWithdrawalMouseEntered
        scaleLabelIcon(lblCashWithdrawal, "/ATM/cash-withdrawal-hover.png");
    }//GEN-LAST:event_lblCashWithdrawalMouseEntered

    private void lblCashWithdrawalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashWithdrawalMouseExited
        scaleLabelIcon(lblCashWithdrawal, "/ATM/cash-withdrawal.png");
    }//GEN-LAST:event_lblCashWithdrawalMouseExited

    private void lblCashWithdrawalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashWithdrawalMouseClicked
        Screen5 screen5 = new Screen5();
        screen5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCashWithdrawalMouseClicked

    private void lblOtherServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtherServicesMouseClicked
        FileHandling.writJSON(200000);
    }//GEN-LAST:event_lblOtherServicesMouseClicked

    private void lblOtherServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtherServicesMouseEntered
        scaleLabelIcon(lblOtherServices, "/ATM/other-services-hover.png");
    }//GEN-LAST:event_lblOtherServicesMouseEntered

    private void lblOtherServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtherServicesMouseExited
        scaleLabelIcon(lblOtherServices, "/ATM/other-services.png");
    }//GEN-LAST:event_lblOtherServicesMouseExited
    
    private void scaleLabelIcon(JLabel lbl, String imagePath) {
        try {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource(imagePath))
                .getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH));
            lbl.setIcon(imageIcon);
        } catch (Exception e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAccountDetails;
    private javax.swing.JLabel lblAvailableAmount;
    private javax.swing.JLabel lblCashWithdrawal;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblFundTransfer;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblOtherServices;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    // End of variables declaration//GEN-END:variables
}
